CREATE TABLE IF NOT EXISTS
BILLIONAIR (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    RANK INT,
    NETWORTH DOUBLE,
    COMPANIESOWNED VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE;