--CREATE TABLE IF NOT EXISTS
--BILLIONAIR(
--    ID INT AUTO_INCREMENT PRIMARY KEY,
--    PICTURE VARCHAR(255),
--   NAME VARCHAR(255),
--    NET_WORTH DOUBLE,
--    COMPANIES_OWNED VARCHAR(255),
--    IMAGE BLOB
--);

