CREATE TABLE IF NOT EXISTS
BILLIONAIR (
    ID INT PRIMARY KEY,
    PICTURE VARCHAR(255),
    NAME VARCHAR(255),
    NET_WORTH DOUBLE,
    COMPANIES_OWNED VARCHAR(255)

);

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE;